feat(ci): add warning for missing trivyignore

diff --git a/.github/actions/check-trivyignore/action.yaml b/.github/actions/check-trivyignore/action.yaml
--- a/.github/actions/check-trivyignore/action.yaml
+++ b/.github/actions/check-trivyignore/action.yaml
@@ -39,17 +39,20 @@ runs:
       run: |
         if [ -f "${{ inputs.trivyignores }}" ]
           then
-            output=$(trivy image ${{ inputs.image-ref }} --severity ${{ inputs.severity }} -q \
-                      -f json --ignorefile "" --skip-files ${{ inputs.skip-files }} \
-                        | jq -r '.Results[].Vulnerabilities[].VulnerabilityID' 2>/dev/null \
-                      || echo "No vulnerabilities found")
+            json_output=$(trivy image ${{ inputs.image-ref }} --severity ${{ inputs.severity }} -q \
+                      -f json --ignorefile "" --skip-files ${{ inputs.skip-files }} --exit-code 0)
+            output=$(echo $json_output | jq -r '.Results[].Vulnerabilities[].VulnerabilityID' \
+                    2>/dev/null \
+                    || echo "No vulnerabilities found")
             line=0
             while read CVE;
             do
               line=$(( line + 1 ))
-              if [[ "$output" != *"$CVE"* ]] && [[ ! "$CVE" =~ ^#.* ]]
+              if [[ "$output" != *"$CVE"* && ! "$CVE" =~ ^#.* ]]
               then
               echo "::notice file=${{ inputs.trivyignores }},line=${line}::$CVE not present anymore, can be safely removed."
               fi
             done < ${{ inputs.trivyignores }}
+          else
+            echo "::warning::File ${{ inputs.trivyignores }} not found."
           fi
