main

diff --git a/.github/workflows/Builds.yaml b/.github/workflows/Builds.yaml
--- a/.github/workflows/Builds.yaml
+++ b/.github/workflows/Builds.yaml
@@ -72,6 +72,22 @@ jobs:
       
       - run: git checkout ${{ matrix.commit }}
 
+      - name: Validate proper image naming
+        if: matrix.dockerfile-build == ''
+        working-directory: ${{ matrix.directory }}
+        env:
+          YQ_VERSION: 'v4.32.2'
+          YQ_BINARY: yq_linux_amd64
+        run: |
+          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O /usr/bin/yq \
+            && chmod +x /usr/bin/yq
+          
+          rock_name=`cat rockcraft.y*ml | yq -r .name`
+          if [[ "${{ matrix.path }}" != *"${rock_name}"* ]]
+            echo "ERROR: the ROCK's name must match the OCI folder name!"
+            exit 1
+          fi
+
       - name: Build ROCK ${{ matrix.name }}
         if: matrix.dockerfile-build == ''
         id: rockcraft
@@ -117,3 +133,8 @@ jobs:
         with:
           name: ${{ matrix.name }}_${{ matrix.commit }}.tar
           path: ${{ matrix.name }}_${{ matrix.commit }}.tar
+
+      - name: Run tests for ${{ matrix.name }} on ${{ matrix.commit }}
+        uses: ./github/workflows/tests
+        with:
+          artifact-name: ${{ matrix.name }}_${{ matrix.commit }}.tar
