feat: add access validation job

diff --git a/.github/workflows/Build-Rock.yaml b/.github/workflows/Build-Rock.yaml
--- a/.github/workflows/Build-Rock.yaml
+++ b/.github/workflows/Build-Rock.yaml
@@ -39,49 +39,67 @@ env:
 
   OCI_FACTORY_REPO: canonical/oci-factory
   # TODO: update before final merge
-  OCI_FACTORY_BRANCH: main  # required for external workflow calls.
+  OCI_FACTORY_BRANCH: ${{ github.repository == 'canonical/oci-factory' && github.ref_name || main }}  # required for external workflow calls.
 
 jobs:
-  configure-build:
-    # configure-build reads the rockcraft.yaml, creating one or more *-build job runs
-    # depending on the target architecture.
+
+  access-validation:
     runs-on: ubuntu-22.04
-    outputs:
-      runner-build-matrix: ${{ steps.configure.outputs.runner-build-matrix }}
-      lpci-build-matrix: ${{ steps.configure.outputs.lpci-build-matrix }}
-      oci-factory-branch: ${{ steps.oci-factory-branch.outputs.branch }}
+    if: ${{ github.repository == 'canonical/oci-factory'  && !github.event.pull_request.head.repo.fork }}
     steps:
 
-      # ** Workflow authorization and job validation **
-      # Checkout the OCI Factory repo for the actor validation
-
-      # move this to an action since it may be used frequently 
-      - name: Select oci-factory branch
-        id: oci-factory-branch
-        run: echo "branch=$(${{ github.repository == 'canonical/oci-factory' }} && echo ${{ github.ref_name }} || echo ${{ env.OCI_FACTORY_BRANCH }})" >> $GITHUB_OUTPUT
-
       - uses: actions/checkout@v4
-        if: ${{ github.repository == 'canonical/oci-factory'  && !github.event.pull_request.head.repo.fork }}
         with:
           repository: ${{ env.OCI_FACTORY_REPO }}
           ref: ${{ steps.configure-build.outputs.branch }}
           fetch-depth: 1
 
+      - name: Clone GitHub image repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.rock-repo }}
+          path: ${{ env.ROCK_REPO_DIR }}
+          ref: ${{ inputs.rock-repo-commit }}
+          submodules: "recursive"
+          fetch-depth: 1
+
       - name: Validate access to triggered image
         uses: ./.github/actions/validate-actor
-        if: ${{ github.repository == 'canonical/oci-factory' && !github.event.pull_request.head.repo.fork }}
         with:
           admin-only: true
           image-path: ${{ inputs.oci-factory-path }}
           github-token: ${{ secrets.ROCKSBOT_TOKEN }}
 
-      # We clear the working directory to make space for the rock repo
-      # - run: rm -rf ./*
-      #   if: ${{ github.repository == 'canonical/oci-factory' && !github.event.pull_request.head.repo.fork }}
+
+      - run: sudo snap install yq --channel=v4/stable
+      - name: Validate image naming and base
+        run: |
+          rock_name=`cat "${{ env.ROCK_REPO_DIR }}/${{ inputs.rockfile-directory }}"/rockcraft.y*ml | yq -r .name`
+          folder_name=`basename "${{ inputs.rockfile-directory }}"`
+          if [[ "${folder_name}" != "${rock_name}" ]]
+          then
+            echo "ERROR: the rock's name '${rock_name}' must match the OCI folder name '${folder_name}'"
+            exit 1
+          fi
+
+  configure-build:
+    # configure-build reads the rockcraft.yaml, creating one or more *-build job runs
+    # depending on the target architecture.
+    needs: [access-validation]
+    runs-on: ubuntu-22.04
+    outputs:
+      runner-build-matrix: ${{ steps.configure.outputs.runner-build-matrix }}
+      lpci-build-matrix: ${{ steps.configure.outputs.lpci-build-matrix }}
+    steps:
+
+      - uses: actions/checkout@v4
+        with:
+          repository: ${{ env.OCI_FACTORY_REPO }}
+          ref: ${{ steps.configure-build.outputs.branch }}
+          fetch-depth: 1
 
       - name: Clone GitHub image repository
         uses: actions/checkout@v4
-        id: clone-image-repo
         continue-on-error: true
         with:
           repository: ${{ inputs.rock-repo }}
@@ -90,22 +108,10 @@ jobs:
           submodules: "recursive"
           fetch-depth: 1
 
-      # - run: sudo snap install yq --channel=v4/stable
-      # - name: Validate image naming and base
-      #   run: |
-      #     rock_name=`cat "${{ env.ROCK_REPO_DIR }}/${{ inputs.rockfile-directory }}"/rockcraft.y*ml | yq -r .name`
-      #     folder_name=`basename "${{ inputs.rockfile-directory }}"`
-      #     if [[ "${folder_name}" != "${rock_name}" ]]
-      #     then
-      #       echo "ERROR: the rock's name '${rock_name}' must match the OCI folder name '${folder_name}'"
-      #       exit 1
-      #     fi
-      # - uses: actions/setup-python@v5
-      #   with:
-      #     python-version: "3.x"
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.x"
 
-      # ** Workflow job configuration **
-      - run: ls -lashR src
       - run: pip install -r src/build_rock/configure/requirements.txt
 
       # Configure matrices for each *-build job
@@ -172,7 +178,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           repository: ${{ env.OCI_FACTORY_REPO }}
-          ref: ${{ needs.configure-build.outputs.oci-factory-branch }}
+          ref: ${{ env.OCI_FACTORY_BRANCH }}
           fetch-depth: 1
 
       - name: Clone Repo
@@ -221,7 +227,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           repository: ${{ env.OCI_FACTORY_REPO }}
-          ref: ${{ needs.configure-build.outputs.oci-factory-branch }}
+          ref: ${{ env.OCI_FACTORY_BRANCH }}
           fetch-depth: 1
 
       - run: src/build_rock/assemble_rock/requirements.sh
