fix: disable image folder validation

diff --git a/.github/workflows/Build-Rock.yaml b/.github/workflows/Build-Rock.yaml
--- a/.github/workflows/Build-Rock.yaml
+++ b/.github/workflows/Build-Rock.yaml
@@ -90,19 +90,19 @@ jobs:
           submodules: "recursive"
           fetch-depth: 1
 
-      - run: sudo snap install yq --channel=v4/stable
-      - name: Validate image naming and base
-        run: |
-          rock_name=`cat "${{ env.ROCK_REPO_DIR }}/${{ inputs.rockfile-directory }}"/rockcraft.y*ml | yq -r .name`
-          folder_name=`basename "${{ inputs.rockfile-directory }}"`
-          if [[ "${folder_name}" != "${rock_name}" ]]
-          then
-            echo "ERROR: the rock's name '${rock_name}' must match the OCI folder name '${folder_name}'"
-            exit 1
-          fi
-      - uses: actions/setup-python@v5
-        with:
-          python-version: "3.x"
+      # - run: sudo snap install yq --channel=v4/stable
+      # - name: Validate image naming and base
+      #   run: |
+      #     rock_name=`cat "${{ env.ROCK_REPO_DIR }}/${{ inputs.rockfile-directory }}"/rockcraft.y*ml | yq -r .name`
+      #     folder_name=`basename "${{ inputs.rockfile-directory }}"`
+      #     if [[ "${folder_name}" != "${rock_name}" ]]
+      #     then
+      #       echo "ERROR: the rock's name '${rock_name}' must match the OCI folder name '${folder_name}'"
+      #       exit 1
+      #     fi
+      # - uses: actions/setup-python@v5
+      #   with:
+      #     python-version: "3.x"
 
       # ** Workflow job configuration **
       - run: pip install -r src/build_rock/configure/requirements.txt
