fix: enforce job conclusion for dispatches

diff --git a/.github/workflows/Image.yaml b/.github/workflows/Image.yaml
--- a/.github/workflows/Image.yaml
+++ b/.github/workflows/Image.yaml
@@ -293,6 +293,14 @@ jobs:
           url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-tests.outputs.run-id }}'
           echo " - Triggered tests for '${{ matrix.name }}' at [${url}](${url})" >> "$GITHUB_STEP_SUMMARY"
 
+      - name: Enforce test conclusion
+        if: ${{ steps.run-tests.outputs.run-conclusion != 'success' }}
+        # The previous step doesn't always raise an error
+        run: |
+          url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-tests.outputs.run-id }}'
+          echo "Testing of image '${{ matrix.oci-image }}' failed at [${url}](${url})."
+          exit 1
+
       # Wait to make sure the test artifacts are uploaded
       - run: sleep 5
 
@@ -512,6 +520,13 @@ jobs:
           url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-releases.outputs.run-id }}'
           echo " - Triggered releases for '${{ needs.prepare-build.outputs.oci-img-name }}' at [${url}](${url})" >> "$GITHUB_STEP_SUMMARY"
 
+      - name: Enforce release conclusion
+        if: ${{ steps.run-releases.outputs.run-conclusion != 'success' }}
+        # The previous step doesn't always raise an error
+        run: |
+          url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-releases.outputs.run-id }}'
+          echo "Failed to release '${{ needs.prepare-build.outputs.oci-img-name }}' at [${url}](${url})."
+          exit 1
 
   generate-provenance:
     name: Generate SLSA provenance
diff --git a/.github/workflows/Release.yaml b/.github/workflows/Release.yaml
--- a/.github/workflows/Release.yaml
+++ b/.github/workflows/Release.yaml
@@ -150,6 +150,20 @@ jobs:
           trigger-timeout: '30m'
           run-id: dummy
 
+      - name: Write step summary
+        run: |
+          url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-documentation.outputs.run-id }}'
+          echo " - Triggered documentation updates for '${{ inputs.oci-image-name }}' at [${url}](${url})" >> "$GITHUB_STEP_SUMMARY"
+
+      - name: Enforce docs conclusion
+        if: ${{ steps.run-documentation.outputs.run-conclusion != 'success' }}
+        # The previous step doesn't always raise an error
+        run: |
+          url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-documentation.outputs.run-id }}'
+          echo "Failed to generate docs for '${{ inputs.oci-image-name }}' at [${url}](${url})."
+          exit 1
+
+
   do-github-release:
     runs-on: ubuntu-22.04
     name: Github-Release
