refactor: move path validation outside of build rock repo

diff --git a/.github/workflows/Image.yaml b/.github/workflows/Image.yaml
--- a/.github/workflows/Image.yaml
+++ b/.github/workflows/Image.yaml
@@ -123,6 +123,20 @@ jobs:
             --oci-path ${{ steps.validate-image.outputs.img-path }} \
             --revision-data-dir ${{ env.DATA_DIR }}
 
+      - name: Installing yq
+        run: sudo snap install yq --channel=v4/stable
+
+      - name: Validate image naming and base
+        run: |
+          rock_name=`cat "${{ env.ROCK_REPO_DIR }}/${{ inputs.rockfile-directory }}"/rockcraft.y*ml | yq -r .name`
+          folder_name="${{ inputs.oci-factory-path }}"
+          if [[ "${folder_name}" != *"${rock_name}"* ]]
+          then
+            echo "ERROR: the OCI folder name '${folder_name}', must contain the rock's name '${rock_name}'."
+            exit 1
+          fi
+
+
   run-build:
     needs: [prepare-build]
     strategy:
