feat(oci): Add generation of documentation data YAML (#26)
* feat(oci): Add generation of documentation

This commit permit to add the generatation of documentation
for the ROCKS build with the oci-factory

score of the file:
generate_oci_documentation.py: Pylint: 10/10 mi: A (54.18) cc: A (2.3333333333333335)
prepare_multi_image_documentation.py: Pylint: 10/10 mi: A (71.88) cc: A (2.0)
triggers.py: Pylint:6.73/10 because the trigger don't have public method for the class mi: A (100) cc: A (1.0)
Docs.yaml and Release.yaml: use of yamlint

Signed_Off_By: Samir Akarioh <samir.akarioh@canonical.com>

* fix: enforce job conclusion for dispatches

* fix: general fixes and optimizations to doc generation

* ci: automatically update oci/mock-docker-image/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5219733155

* ci: automatically update oci/mock-rock/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5219793742

* fix: bad workflow name and upload docs

* ci: automatically update oci/mock-docker-image/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5220101950

* ci: automatically update oci/mock-rock/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5220102595

* ci: split doc trigger into its own job

* ci: automatically update oci/mock-docker-image/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5220452328

* ci: automatically update oci/mock-rock/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5220468042

* ci: trigger Documentation wf via push

* ci: run Documentation wf on any branch

* ci: trigger Documentation wf via push

* fix: typo in workflow

* ci: automatically update oci/mock-rock/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5220839167

* ci: automatically update oci/mock-docker-image/_releases.json, from https://github.com/canonical/oci-factory/actions/runs/5220841058

---------

Co-authored-by: Cristovao Cordeiro <cristovao.cordeiro@canonical.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@localhost>

diff --git a/.github/workflows/Release.yaml b/.github/workflows/Release.yaml
--- a/.github/workflows/Release.yaml
+++ b/.github/workflows/Release.yaml
@@ -49,6 +49,8 @@ jobs:
             exit 1
           fi
           echo "img-name=$(basename ${img_dir})" >> "$GITHUB_OUTPUT"
+
+  
   do-releases:
     runs-on: ubuntu-22.04
     name: Release
@@ -129,11 +131,45 @@ jobs:
       - name: Commit oci/${{ inputs.oci-image-name }}/_releases.json
         uses: actions-x/commit@v6
         with:
-          token: ${{ secrets.ROCKSBOT_TOKEN }}
+          token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
           message: 'ci: automatically update oci/${{ inputs.oci-image-name }}/_releases.json, from ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
           files: oci/${{ inputs.oci-image-name }}/_releases.json
-          email: rocks-dev@lists.canonical.com
+
+
+  dispatch-documentation:
+    runs-on: ubuntu-22.04
+    name: Dispatch documentation
+    needs: [do-releases]
+    steps:
+      - name: Run documentation
+        # Using this actions cause others can have this problem:
+        # https://github.com/convictional/trigger-workflow-and-wait/issues/61
+        uses: mathze/workflow-dispatch-action@v1.2.0
+        id: run-documentation
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          ref: ${{ github.ref_name }}
+          fail-on-error: true
+          workflow-name: Documentation.yaml
+          payload: '{ "oci-image-name": "${{ inputs.oci-image-name }}"}'
+          use-marker-step: true
+          trigger-timeout: '30m'
+          run-id: dummy
+
+      - name: Write step summary
+        run: |
+          url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-documentation.outputs.run-id }}'
+          echo " - Triggered documentation updates for '${{ inputs.oci-image-name }}' at [${url}](${url})" >> "$GITHUB_STEP_SUMMARY"
+
+      - name: Enforce docs conclusion
+        if: ${{ steps.run-documentation.outputs.run-conclusion != 'success' }}
+        # The previous step doesn't always raise an error
+        run: |
+          url='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.run-documentation.outputs.run-id }}'
+          echo "Failed to generate docs for '${{ inputs.oci-image-name }}' at [${url}](${url})."
+          exit 1
+
 
   do-github-release:
     runs-on: ubuntu-22.04
@@ -171,4 +207,3 @@ jobs:
           name: "${{ matrix.release-name }}"
           tag_name: "${{ matrix.release-name }}"
           token: "${{ secrets.GITHUB_TOKEN }}"
-          
